# Generated by Django 3.0.4 on 2022-01-21 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('is_active', models.CharField(blank=True, choices=[('0', 'Desactivo'), ('1', 'Activo')], default='1', max_length=80, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Trámite',
                'verbose_name_plural': 'Tipos de Trámites',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Dirección')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('document_number', models.IntegerField(blank=True, null=True, verbose_name='Número de Documento')),
                ('folio_number', models.IntegerField(blank=True, null=True, verbose_name='Número de Folio')),
                ('subject', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Asunto')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tramite/archivo', verbose_name='Archivo')),
                ('observation', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Observación')),
                ('state', models.CharField(blank=True, choices=[('0', 'Desactivo'), ('1', 'Activo')], default='1', max_length=80, null=True, verbose_name='Estado')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.TipoTramite', verbose_name='Tipo de Trámite')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['id'],
            },
        ),
    ]
